### PR TITLE
TFW-3726 - Bookmark loading indicator

### PR DESCRIPTION
**Pull request by tVeratti**

### CODE REVIEW

**Comment by tVeratti** [comment]
> code looks good, but trying to play with the demo I get
> 
> ```
>     at BookmarkModal (VM23851 1398:47)
>     at renderWithHooks (VM22586 14:12892)
>     at mountIndeterminateComponent (VM22586 14:14974)
>     at beginWork (VM22586 14:15579)
>     at performUnitOfWork (VM22586 14:19266)
>     at workLoop (VM22586 14:19306)
>     at renderRoot (VM22586 14:19389)
>     at performWorkOnRoot (VM22586 14:20296)
>     at performWork (VM22586 14:20208)
>     at performSyncWork (VM22586 14:20182)```
> ```

Very odd, it was rendering fine for me. Will check this out!

**Comment by troyblank** [comment]
> > code looks good, but trying to play with the demo I get
> > ```
> >     at BookmarkModal (VM23851 1398:47)
> >     at renderWithHooks (VM22586 14:12892)
> >     at mountIndeterminateComponent (VM22586 14:14974)
> >     at beginWork (VM22586 14:15579)
> >     at performUnitOfWork (VM22586 14:19266)
> >     at workLoop (VM22586 14:19306)
> >     at renderRoot (VM22586 14:19389)
> >     at performWorkOnRoot (VM22586 14:20296)
> >     at performWork (VM22586 14:20208)
> >     at performSyncWork (VM22586 14:20182)```
> > ```
> 
> Very odd, it was rendering fine for me. Will check this out!

Yea, i tried again this morning to make sure I didn't' do anything wrong but still seeing it.

Screen Shot 2019-06-13 at 10 10 15 AM

**Comment by tVeratti** [comment]
@troyblank fixed the demo issue :)

**Comment by troyblank** [comment]
@tVeratti  cool sorry to keep this going, but what happens if a user clicks on "view all interactions" while the bookmark is loading? shouldn't this be a more full take over of all of search?

**Pull request merged**
