### PR TITLE
TFW-4010 - Manage Bookmarks appearance fixes

### PR DESCRIPTION
**Pull request by jasonhale**
- fixed a capitalization
- modifed HeaderPane for instances of backLink
- fixed content getting cutoff on Manage Bookmarks

### CODE REVIEW

**Comment by jasonhale** [comment]
@troyblank - updated for Manage Bookmarks header breakpoints.

**Comment by troyblank** [comment]
@jasonhale  still seems it's got some issues, other than this small spot it is awesome.

Screen Shot 2019-07-01 at 8 54 00 AM
 
vs what's on dev

Screen Shot 2019-07-01 at 8 54 41 AM


Sorry but it seems like even having the title in the middle is a better option than creating scrollbars for a long tittle.

**Comment by jasonhale** [comment]
WTH.  Thought I covered all that.  Alright - just a min...

**Comment by jasonhale** [comment]
@troyblank - fixed.

Screen Shot 2019-07-01 at 9 20 13 AM

**Comment by jasonhale** [comment]
yessss

**Pull request merged**
