### PR TITLE
Use Jenkins instead of Travis

### PR DESCRIPTION
**Pull request by mathom**
Check the build log if you don't mind. I'm concerned about this (it appears to just be a deprecation but I'd like a second opinion):

```
  Meta Modal
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Not-A-Date 1:00pm, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:324:94)
    at configFromString (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:2364:11)
    at configFromInput (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:2590:9)
    at prepareConfig (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:2573:9)
    at createFromConfig (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:2540:40)
    at createLocalOrUTC (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:2627:12)
    at createLocal (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:2631:12)
    at hooks (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/moment/moment.js:16:25)
    at convertToLocalTime (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/components/interactionEditor/util.js:1:62816)
    at /home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/components/interactionEditor/modals/metaModal.js:1:4839
    at Array.map (<anonymous>)
    at MetaModal (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/components/interactionEditor/modals/metaModal.js:1:4613)
    at /home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:306:16
    at measureLifeCyclePerf (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:305:14)
    at ReactCompositeComponentWrapper._constructComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)
    at ReactCompositeComponentWrapper.mountComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
    at Object.mountComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at mountComponentIntoNode (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactMount.js:104:32)
    at ReactReconcileTransaction.perform (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/Transaction.js:140:20)
    at batchedMountComponentIntoNode (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactMount.js:126:15)
    at ReactDefaultBatchingStrategyTransaction.perform (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at Object._renderNewRootComponent (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactMount.js:320:18)
    at Object._renderSubtreeIntoContainer (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactMount.js:401:32)
    at Object.render (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactMount.js:422:23)
    at Object.renderIntoDocument (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/react-dom/lib/ReactTestUtils.js:91:21)
    at renderWithOptions (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/enzyme/build/react-compat.js:209:26)
    at new ReactWrapper (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/enzyme/build/ReactWrapper.js:94:59)
    at mount (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/enzyme/build/mount.js:19:10)
    at Context.<anonymous> (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/test/components/interactionEditor/modals/metaModal.spec.js:24:25)
    at callFn (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runnable.js:345:21)
    at Test.Runnable.run (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runnable.js:337:7)
    at Runner.runTest (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runner.js:444:10)
    at /home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runner.js:550:12
    at next (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runner.js:361:14)
    at /home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runner.js:371:7
    at next (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runner.js:295:14)
    at Immediate._onImmediate (/home/jenkins/workspace/opbox_rci-components_PR-602-O5WJSKNR7OFIRKJYADSG2A7MSSFKOZBBLJTIK76GC2B2A76LV7VQ/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    ✓ should render

```

### CODE REVIEW

**Comment by mathom** [comment]
[100% (+100.0%) vs master 0%](https://jenkins.topbox.io/job/Topbox/job/rci-components/job/PR-602/15/)

**Comment by mathom** [comment]
[100% (+100.0%) vs master 0%](https://jenkins.topbox.io/job/Topbox/job/rci-components/job/PR-602/16/)

**Comment by mathom** [comment]
[100% (+100.0%) vs master 0%](https://jenkins.topbox.io/job/Topbox/job/rci-components/job/PR-602/17/)

**Comment by troyblank** [comment]
@mathom  yea that depreciation has happened a lot, I would not worry about it right now. We need to go in and clean stuff up for sure but at this time we are just living with it.

**Pull request merged**
